//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudORMentity.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetallesCompra = new HashSet<DetallesCompra>(); // HashSet es una colección que no permite elementos duplicados 
            this.DetallesFactura = new HashSet<DetallesFactura>();
        }
    
        public int ProductoID { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public int CategoriaID { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesCompra> DetallesCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesFactura> DetallesFactura { get; set; } // ICollection es una interfaz que define una colección genérica de objetos con metodos para agregar, raestrar y eliminar relaciones.
    }
}

/* “Lazy loading en EF funciona como un sistema de carga bajo demanda:
 * las entidades relacionadas se traen desde la base de datos solo cuando se acceden.
 * Para lograr esto, EF crea proxies dinámicos que actúan como dobles de las entidades,
 * interceptando el acceso a propiedades virtual y lanzando consultas automáticas. Es como tener un camarero invisible
 * que te sirve justo cuando lo necesitás, sin cargar todo desde el inicio.” */


/* EF crea un proxy dinámico: una subclase en tiempo de ejecución que hereda de tu clase original (Producto, Cliente, etc.).

Este proxy intercepta el acceso a propiedades virtual.

Cuando accedés a producto.DetallesCompra, el proxy detecta que no está cargado y lanza una consulta SQL automáticamente.

Esto solo funciona si:

La propiedad es virtual.

Lazy loading está habilitado.*/

